create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  amount numeric not null,
  payment_method text not null,
  billing_country text,
  ip_country text,
  model_prediction integer not null,
  model_fraud_score numeric not null,
  fraud_score numeric not null,
  status text not null,
  gateway text,
  routing_reason text,
  risk_adjustment_reasons jsonb default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists transactions_user_id_created_at_idx
  on public.transactions (user_id, created_at desc);
